version: 0.2

phases:
  install:
    runtine-versions:
      nodejs: 16
    commands:
      - echo Installing dependency...
      - npm install
  build:
    commands:
      - echo Compiling the Node.js code
      - npm run-script build
  post_build:
    commands:
      - echo Build completed
      - aws s3 cp build s3://elasticbeanstalk-us-east-2-611071826990 --recursive --acl public-read
